[
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "PRESIDENTA (PRI)",
        "Extension": "8270",
        "Titulo": "DIP.",
        "NombreCompleto": "GUERRA CASTILLO MARCELA  ",
        "Nombre": "GUERRA CASTILLO MARCELA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "marcela.guerra@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 1,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIO TÉCNICO",
        "Extension": "5033",
        "Titulo": null,
        "NombreCompleto": "PENDIENTE POR NOMBRAMIENTO  ",
        "Nombre": "PENDIENTE POR NOMBRAMIENTO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": null,
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 2,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "COORDINADORA ADMINISTRATIVA",
        "Extension": "2203",
        "Titulo": "LIC.",
        "NombreCompleto": "ARROYO GALA VERÓNICA YOLANDA  ",
        "Nombre": "ARROYO GALA VERÓNICA YOLANDA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "veronica.arroyo@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 4,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "COORDINADOR DE ASESORES",
        "Extension": "53108",
        "Titulo": null,
        "NombreCompleto": "PENDIENTE POR NOMBRAMIENTO  ",
        "Nombre": "PENDIENTE POR NOMBRAMIENTO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": null,
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 5,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "VICEPRESIDENTA    (MORENA)",
        "Extension": "8322",
        "Titulo": "DIP.",
        "NombreCompleto": "ALMAZÁN BURGOS KARLA YURITZI  ",
        "Nombre": "ALMAZÁN BURGOS KARLA YURITZI",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "karla.almazan@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 13,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "VICEPRESIDENTA    (PAN)",
        "Extension": "5076",
        "Titulo": "DIP.",
        "NombreCompleto": "FELIPE TORRES JOANNA ALEJANDRA  ",
        "Nombre": "FELIPE TORRES JOANNA ALEJANDRA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "joanna.felipe@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 14,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "VICEPRESIDENTA    (PRI)",
        "Extension": "5029",
        "Titulo": "DIP.",
        "NombreCompleto": "ALCALÁ RUIZ BLANCA MARÍA DEL SOCORRO  ",
        "Nombre": "ALCALÁ RUIZ BLANCA MARÍA DEL SOCORRO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "blanca.alcala@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 15,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIA   (MORENA)",
        "Extension": "53109",
        "Titulo": "DIP.",
        "NombreCompleto": "ESPINOZA LÓPEZ BRENDA  ",
        "Nombre": "ESPINOZA LÓPEZ BRENDA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "brenda.espinoza@diputados.gob.mx",
        "Edificio": "C",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 16,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIA    (PAN)",
        "Extension": "8310",
        "Titulo": "DIP.",
        "NombreCompleto": "GUTIÉRREZ VALTIERRA DIANA ESTEFANÍA  ",
        "Nombre": "GUTIÉRREZ VALTIERRA DIANA ESTEFANÍA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "estefania.gutierrez@diputados.gob.mx",
        "Edificio": "G",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 17,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIA    (PRI)",
        "Extension": "8268",
        "Titulo": "DIP.",
        "NombreCompleto": "GUERRERO ESQUIVEL FUENSANTA GUADALUPE  ",
        "Nombre": "GUERRERO ESQUIVEL FUENSANTA GUADALUPE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "fuensanta.guerrero@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 18,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIA    (PVEM)",
        "Extension": "5080",
        "Titulo": "DIP.",
        "NombreCompleto": "FERNÁNDEZ CRUZ NAYELI ARLEN  ",
        "Nombre": "FERNÁNDEZ CRUZ NAYELI ARLEN",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "nayeli.fernandez@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 19,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIO    (PT)",
        "Extension": "53007",
        "Titulo": "DIP.",
        "NombreCompleto": "VÁZQUEZ GONZÁLEZ PEDRO  ",
        "Nombre": "VÁZQUEZ GONZÁLEZ PEDRO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "pedro.vazquez@diputados.gob.mx",
        "Edificio": "C",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 20,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIA    (MOV. CIUD.)",
        "Extension": "53068",
        "Titulo": "DIP.",
        "NombreCompleto": "ORTEGA DE LA CRUZ JESSICA MARÍA GUADALUPE  ",
        "Nombre": "ORTEGA DE LA CRUZ JESSICA MARÍA GUADALUPE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jessica.ortega@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 21,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 1,
        "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
        "Cargo": "SECRETARIA    (PRD)",
        "Extension": "5078",
        "Titulo": "DIP.",
        "NombreCompleto": "ESPINOSA MORALES OLGA LUZ  ",
        "Nombre": "ESPINOSA MORALES OLGA LUZ",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "olga.espinosa@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 22,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 2,
        "Area": "JUNTA DE COORDINACIÓN POLÍTICA",
        "Cargo": "PRESIDENTE    (PAN)",
        "Extension": "1862",
        "Titulo": "DIP.",
        "NombreCompleto": "ROMERO HERRERA JORGE  ",
        "Nombre": "ROMERO HERRERA JORGE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jromero.herrera@diputados.gob.mx",
        "Edificio": "G",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 23,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 2,
        "Area": "JUNTA DE COORDINACIÓN POLÍTICA",
        "Cargo": "SECRETARIO DE ENLACE",
        "Extension": "4240",
        "Titulo": "LIC.",
        "NombreCompleto": "SÁNCHEZ MOLINA JOSÉ OMAR  ",
        "Nombre": "SÁNCHEZ MOLINA JOSÉ OMAR",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jose.sanchez@diputados.gob.mx",
        "Edificio": "G",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 24,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "TITULAR DE LA UNIDAD DE TRANSPARENCIA",
        "Extension": "8132",
        "Titulo": "MTRO.",
        "NombreCompleto": "ÁLVAREZ MONTIEL RICARDO  ",
        "Nombre": "ÁLVAREZ MONTIEL RICARDO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "ricardo.alvarez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 27,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "DIRECTOR DE ATENCIÓN A SOLICITUDES Y RECURSOS DE REVISIÓN",
        "Extension": "66149",
        "Titulo": "LIC.",
        "NombreCompleto": "ROJAS SÁNCHEZ LUIS DANIEL  ",
        "Nombre": "ROJAS SÁNCHEZ LUIS DANIEL",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "luis.rojas@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 28,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "SUBDIRECTORA DE ACCESO A LA INFORMACIÓN, DERECHOS ARCO Y MEDIO DE IMPUGNACIÓN",
        "Extension": "8129",
        "Titulo": "LIC.",
        "NombreCompleto": "JIMÉNEZ ZARIÑÁN YESSICA  ",
        "Nombre": "JIMÉNEZ ZARIÑÁN YESSICA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "yessica.jimenez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 29,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "DIRECTORA DE TRANSPARENCIA, COORDINACIÓN INTERINSTITUCIONAL, NORMATIVIDAD Y CAPACITACIÓN",
        "Extension": "55032",
        "Titulo": "MTRA.",
        "NombreCompleto": "CASTILLO POSADA JACQUELINE  ",
        "Nombre": "CASTILLO POSADA JACQUELINE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jacqueline.castillo@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 32,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "SUBDIRECTOR DE TRANSPARENCIA, COORDINACIÓN INTERINSTITUCIONAL, NORMATIVIDAD Y CAPACITACIÓN",
        "Extension": "55085",
        "Titulo": "LIC.",
        "NombreCompleto": "GONZÁLEZ MEDINA IRVING  ",
        "Nombre": "GONZÁLEZ MEDINA IRVING",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "irving.gonzalez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 33,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "DIRECTORA DE DATOS PERSONALES, ARCHIVO Y GESTIÓN DOCUMENTAL",
        "Extension": "62152",
        "Titulo": "LIC.",
        "NombreCompleto": "AGUILERA ORTA VERÓNICA  ",
        "Nombre": "AGUILERA ORTA VERÓNICA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "veronica.aguilera@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 36,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 3,
        "Area": "UNIDAD DE TRANSPARENCIA DE LA CÁMARA DE DIPUTADOS",
        "Cargo": "SUBDIRECTORA DE DATOS PERSONALES, ARCHIVO Y GESTIÓN DOCUMENTAL",
        "Extension": "67306",
        "Titulo": "LIC.",
        "NombreCompleto": "SANTILLÁN ARANDA YURITZI ALEJANDRA  ",
        "Nombre": "SANTILLÁN ARANDA YURITZI ALEJANDRA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "yuritzi.santillan@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 37,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 4,
        "Area": "COMITÉ DE TRANSPARENCIA",
        "Cargo": "DIRECTORA DE ENLACE Y ATENCIÓN DE LOS ASUNTOS ENCOMENDADOS AL COMITÉ DE TRANSPARENCIA",
        "Extension": "55299",
        "Titulo": "LIC.",
        "NombreCompleto": "ARMENDÁRIZ VALVERDE ALIN DE GUADALUPE  ",
        "Nombre": "ARMENDÁRIZ VALVERDE ALIN DE GUADALUPE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "alin.armendariz@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 2",
        "Fotografia": null,
        "OrdenPuesto": 39,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 5,
        "Area": "COORDINACIÓN DE COMUNICACIÓN SOCIAL",
        "Cargo": "COORDINADOR",
        "Extension": "1339",
        "Titulo": "LIC.",
        "NombreCompleto": "ARVIZU MARÍN EDUARDO ANTONIO  ",
        "Nombre": "ARVIZU MARÍN EDUARDO ANTONIO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "eduardo.arvizu@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 41,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 5,
        "Area": "COORDINACIÓN DE COMUNICACIÓN SOCIAL",
        "Cargo": "COORDINADORA TÉCNICA",
        "Extension": "1338",
        "Titulo": "LIC.",
        "NombreCompleto": "PULIDO TEJEDA PATRICIA  ",
        "Nombre": "PULIDO TEJEDA PATRICIA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": null,
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 43,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 6,
        "Area": "DIRECCIÓN GENERAL DE INFORMACIÓN",
        "Cargo": "DIRECTOR GENERAL",
        "Extension": "1332",
        "Titulo": "LIC.",
        "NombreCompleto": "GÓMEZ HERRERA ALFONSO  ",
        "Nombre": "GÓMEZ HERRERA ALFONSO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "alfonso.gomez@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 45,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 7,
        "Area": "DIRECCIÓN DE INFORMACIÓN",
        "Cargo": "DIRECTORA",
        "Extension": "2155",
        "Titulo": "LIC.",
        "NombreCompleto": "CRUZ LAZCANO MARÍA GUADALUPE  ",
        "Nombre": "CRUZ LAZCANO MARÍA GUADALUPE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "guadalupec.lazcano@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 46,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 7,
        "Area": "DIRECCIÓN DE INFORMACIÓN",
        "Cargo": "SUBDIRECTOR DE INFORMACIÓN",
        "Extension": "2101",
        "Titulo": "LIC.",
        "NombreCompleto": "CRUZ PÉREZ FÉLIX MARIANO  ",
        "Nombre": "CRUZ PÉREZ FÉLIX MARIANO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "mariano.cruz@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 47,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 7,
        "Area": "DIRECCIÓN DE INFORMACIÓN",
        "Cargo": "SUBDIRECTOR DE SÍNTESIS INFORMATIVA",
        "Extension": "1364",
        "Titulo": "LIC.",
        "NombreCompleto": "CASTRO OJEDA HERMENEGILDO  ",
        "Nombre": "CASTRO OJEDA HERMENEGILDO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": null,
        "Edificio": "C",
        "Piso": "BASA.",
        "Fotografia": null,
        "OrdenPuesto": 51,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 7,
        "Area": "DIRECCIÓN DE INFORMACIÓN",
        "Cargo": "SUBDIRECTOR DE AGENCIA DE NOTICIAS",
        "Extension": "2111",
        "Titulo": "C.",
        "NombreCompleto": "CARRASCO ARAIZAGA NORBERTO  ",
        "Nombre": "CARRASCO ARAIZAGA NORBERTO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "norberto.carrasco@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 54,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 8,
        "Area": "DIRECCIÓN DE RELACIONES PÚBLICAS",
        "Cargo": "DIRECTOR",
        "Extension": "2191",
        "Titulo": "C.",
        "NombreCompleto": "VALENCIA LABASTIDA CARLOS  ",
        "Nombre": "VALENCIA LABASTIDA CARLOS",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "carlos.valencia@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 55,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 9,
        "Area": "DIRECCIÓN GENERAL EDITORIAL Y DE IMAGEN LEGISLATIVA",
        "Cargo": "DIRECTORA GENERAL",
        "Extension": "1464",
        "Titulo": "MTRA.",
        "NombreCompleto": "RIQUELME FERNÁNDEZ ROCÍO ETHEL  ",
        "Nombre": "RIQUELME FERNÁNDEZ ROCÍO ETHEL",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "ethel.riquelme@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 58,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 10,
        "Area": "DIRECCIÓN DE DIFUSIÓN",
        "Cargo": "DIRECTORA",
        "Extension": "1354",
        "Titulo": "LIC.",
        "NombreCompleto": "MAGALLANES ALVA MARTHA HILDA  ",
        "Nombre": "MAGALLANES ALVA MARTHA HILDA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "martha.magallanes@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 3",
        "Fotografia": null,
        "OrdenPuesto": 59,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 10,
        "Area": "DIRECCIÓN DE DIFUSIÓN",
        "Cargo": "SUBDIRECTOR DE RADIO Y TELEVISIÓN",
        "Extension": "2107",
        "Titulo": "LIC.",
        "NombreCompleto": "DOMÍNGUEZ CORDERO JOSÉ ARNULFO  ",
        "Nombre": "DOMÍNGUEZ CORDERO JOSÉ ARNULFO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jose.dominguez@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "BASA.",
        "Fotografia": null,
        "OrdenPuesto": 60,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 10,
        "Area": "DIRECCIÓN DE DIFUSIÓN",
        "Cargo": "SUBDIRECTOR DE PRODUCCIÓN",
        "Extension": "5005",
        "Titulo": "LIC.",
        "NombreCompleto": "PÉREZ MÉNDEZ CARLOS ALBERTO  ",
        "Nombre": "PÉREZ MÉNDEZ CARLOS ALBERTO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "carlosalberto.perez@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 3",
        "Fotografia": null,
        "OrdenPuesto": 61,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 10,
        "Area": "DIRECCIÓN DE DIFUSIÓN",
        "Cargo": "SUBDIRECTOR DE TRANSMISIÓN Y OPERACIÓN",
        "Extension": "6024",
        "Titulo": "LIC.",
        "NombreCompleto": "VILLANUEVA YÁÑEZ ALEJANDRO  ",
        "Nombre": "VILLANUEVA YÁÑEZ ALEJANDRO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "alejandro.villanueva@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "PISO 3",
        "Fotografia": null,
        "OrdenPuesto": 64,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 10,
        "Area": "DIRECCIÓN DE DIFUSIÓN",
        "Cargo": "SUBDIRECTOR DE PUBLICIDAD",
        "Extension": "2160",
        "Titulo": "C.",
        "NombreCompleto": "ITURBE VELÁZQUEZ RODOLFO  ",
        "Nombre": "ITURBE VELÁZQUEZ RODOLFO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "rodolfo.iturbide@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "P.BAJA",
        "Fotografia": null,
        "OrdenPuesto": 66,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 11,
        "Area": "DIRECCIÓN DE ADMINISTRACIÓN DE COMUNICACIÓN SOCIAL",
        "Cargo": "DIRECTOR",
        "Extension": "1395",
        "Titulo": "LIC.",
        "NombreCompleto": "SALCEDA RUANOVA JORGE  ",
        "Nombre": "SALCEDA RUANOVA JORGE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jorge.salceda@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "BASA.",
        "Fotografia": null,
        "OrdenPuesto": 69,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 11,
        "Area": "DIRECCIÓN DE ADMINISTRACIÓN DE COMUNICACIÓN SOCIAL",
        "Cargo": "SUBDIRECTOR DE RECURSOS HUMANOS Y CONTABILIDAD",
        "Extension": "52167",
        "Titulo": "C.P.",
        "NombreCompleto": "SÁNCHEZ REBOLLAR CARLOS ALBERTO  ",
        "Nombre": "SÁNCHEZ REBOLLAR CARLOS ALBERTO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "carlos.rebollar@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "BASA.",
        "Fotografia": null,
        "OrdenPuesto": 70,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 11,
        "Area": "DIRECCIÓN DE ADMINISTRACIÓN DE COMUNICACIÓN SOCIAL",
        "Cargo": "SUBDIRECTOR DE RECURSOS  MATERIALES Y SERVICIOS",
        "Extension": "51153",
        "Titulo": "LIC.",
        "NombreCompleto": "MARTÍNEZ GUERRERO ARTURO  ",
        "Nombre": "MARTÍNEZ GUERRERO ARTURO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "arturo.martinez@diputados.gob.mx",
        "Edificio": "A",
        "Piso": "BASA.",
        "Fotografia": null,
        "OrdenPuesto": 72,
        "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 12,
        "Area": "SECRETARÍA GENERAL",
        "Cargo": "SECRETARIA GENERAL",
        "Extension": "5014",
        "Titulo": "LIC.",
        "NombreCompleto": "BÁEZ RICÁRDEZ GRACIELA  ",
        "Nombre": "BÁEZ RICÁRDEZ GRACIELA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "graciela.baez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 1",
        "Fotografia": null,
        "OrdenPuesto": 75,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 12,
        "Area": "SECRETARÍA GENERAL",
        "Cargo": "COORDINADOR DE ASESORES",
        "Extension": "4469",
        "Titulo": "DR.",
        "NombreCompleto": "FLORES MEZA JOSÉ RUBÉN  ",
        "Nombre": "FLORES MEZA JOSÉ RUBÉN",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "ruben.flores@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 1",
        "Fotografia": null,
        "OrdenPuesto": 78,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 13,
        "Area": "DIRECCIÓN GENERAL DE ASUNTOS JURÍDICOS",
        "Cargo": "DIRECTOR GENERAL",
        "Extension": "54106",
        "Titulo": "MTRO.",
        "NombreCompleto": "VÁSQUEZ RODRÍGUEZ LUIS GENARO  ",
        "Nombre": "VÁSQUEZ RODRÍGUEZ LUIS GENARO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "genaro.vasquez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 86,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 13,
        "Area": "DIRECCIÓN GENERAL DE ASUNTOS JURÍDICOS",
        "Cargo": "COORDINADOR  TÉCNICO",
        "Extension": "54101",
        "Titulo": "MTRO.",
        "NombreCompleto": "CURIEL HERNANDEZ JOSÉ ANTONIO  ",
        "Nombre": "CURIEL HERNANDEZ JOSÉ ANTONIO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "antonio.curiel@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 87,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 13,
        "Area": "DIRECCIÓN GENERAL DE ASUNTOS JURÍDICOS",
        "Cargo": "SUBDIRECTORA DE ASUNTOS JURÍDICOS",
        "Extension": "54103",
        "Titulo": "MTRA.",
        "NombreCompleto": "HERNÁNDEZ RAMÍREZ ANA MONSERRAT  ",
        "Nombre": "HERNÁNDEZ RAMÍREZ ANA MONSERRAT",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "monserrat.hernandez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 88,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 14,
        "Area": "DIRECCIÓN DE SERVICIOS LEGALES",
        "Cargo": "DIRECTOR",
        "Extension": "54134",
        "Titulo": "MTRO.",
        "NombreCompleto": "PICHARDO MORA OLINSSER ELIHU  ",
        "Nombre": "PICHARDO MORA OLINSSER ELIHU",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "olinsser.pichardo@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 95,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 14,
        "Area": "DIRECCIÓN DE SERVICIOS LEGALES",
        "Cargo": "SUBDIRECTORA DE APOYO NORMATIVO",
        "Extension": "54233",
        "Titulo": "MTRA.",
        "NombreCompleto": "AZAR CRUZ CLAUDIA VIOLETA  ",
        "Nombre": "AZAR CRUZ CLAUDIA VIOLETA",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "claudia.azar@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 96,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 14,
        "Area": "DIRECCIÓN DE SERVICIOS LEGALES",
        "Cargo": "SUBDIRECTOR DE CONTRATOS Y CONVENIOS",
        "Extension": "54082",
        "Titulo": "LIC.",
        "NombreCompleto": "VÁZQUEZ RAZO JUAN CARLOS  ",
        "Nombre": "VÁZQUEZ RAZO JUAN CARLOS",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "juan.vazquez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 97,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 15,
        "Area": "DIRECCIÓN DE LO CONSULTIVO Y ASESORÍA JURÍDICA",
        "Cargo": "DIRECTOR",
        "Extension": "68382",
        "Titulo": "DR.",
        "NombreCompleto": "RUIZ MUNILLA JOSÉ DE JESÚS  ",
        "Nombre": "RUIZ MUNILLA JOSÉ DE JESÚS",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "jesus.ruiz@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 100,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 15,
        "Area": "DIRECCIÓN DE LO CONSULTIVO Y ASESORÍA JURÍDICA",
        "Cargo": "SUBDIRECTOR DE LO CONSULTIVO Y ASESORÍA JURÍDICA",
        "Extension": "68382",
        "Titulo": "LIC.",
        "NombreCompleto": "RUIZ RAMÍREZ JOSIMAR NASAE  ",
        "Nombre": "RUIZ RAMÍREZ JOSIMAR NASAE",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "josimar.ruiz@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 101,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 16,
        "Area": "DIRECCIÓN DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
        "Cargo": "DIRECTOR",
        "Extension": "54158",
        "Titulo": "MTRO.",
        "NombreCompleto": "LÓPEZ FALCÓN EDUARDO  ",
        "Nombre": "LÓPEZ FALCÓN EDUARDO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "eduardo.lopez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 102,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 16,
        "Area": "DIRECCIÓN DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
        "Cargo": "SUBDIRECTOR DE CONTROVERSIAS Y PROCEDIMIENTOS CONSTITUCIONALES",
        "Extension": "54122",
        "Titulo": "LIC.",
        "NombreCompleto": "RUIZ ARIAS SERGIO  ",
        "Nombre": "RUIZ ARIAS SERGIO",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "sergio.ruiz@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 103,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 16,
        "Area": "DIRECCIÓN DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
        "Cargo": "SUBDIRECTOR DE AMPAROS",
        "Extension": "54153",
        "Titulo": "LIC.",
        "NombreCompleto": "URIBE MEJÍA JUAN  ",
        "Nombre": "URIBE MEJÍA JUAN",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "juan.uribe@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 104,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      },
      {
        "OrdenArea": 16,
        "Area": "DIRECCIÓN DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
        "Cargo": "SUBDIRECTOR DE ASUNTOS LABORALES",
        "Extension": "54152",
        "Titulo": "LIC.",
        "NombreCompleto": "PÉREZ APARICIO ÁNGEL MARTÍN  ",
        "Nombre": "PÉREZ APARICIO ÁNGEL MARTÍN",
        "APaterno": null,
        "Amaterno": null,
        "Correo": "angel.perez@diputados.gob.mx",
        "Edificio": "E",
        "Piso": "PISO 4",
        "Fotografia": null,
        "OrdenPuesto": 105,
        "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
        "__typename": "DirectorioFull"
      }
]
