// Fuente pública: https://micrositios.diputados.gob.mx:4001/graphql

var personal = [
    {
      "id": 1,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "PRESIDENTA (PRI)",
      "Extension": "8270",
      "Titulo": "DIP.",
      "NombreCompleto": "GUERRA CASTILLO MARCELA  ",
      "Nombre": "GUERRA CASTILLO MARCELA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "marcela.guerra@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 1,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 2,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIO T�CNICO",
      "Extension": "5033",
      "Titulo": null,
      "NombreCompleto": "PENDIENTE POR NOMBRAMIENTO  ",
      "Nombre": "PENDIENTE POR NOMBRAMIENTO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": null,
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 2,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 3,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "COORDINADORA ADMINISTRATIVA",
      "Extension": "2203",
      "Titulo": "LIC.",
      "NombreCompleto": "ARROYO GALA VER�NICA YOLANDA  ",
      "Nombre": "ARROYO GALA VER�NICA YOLANDA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "veronica.arroyo@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 4,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 4,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "COORDINADOR DE ASESORES",
      "Extension": "53108",
      "Titulo": null,
      "NombreCompleto": "PENDIENTE POR NOMBRAMIENTO  ",
      "Nombre": "PENDIENTE POR NOMBRAMIENTO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": null,
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 5,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 5,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "VICEPRESIDENTA    (MORENA)",
      "Extension": "8322",
      "Titulo": "DIP.",
      "NombreCompleto": "ALMAZ�N BURGOS KARLA YURITZI  ",
      "Nombre": "ALMAZ�N BURGOS KARLA YURITZI",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "karla.almazan@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 13,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 6,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "VICEPRESIDENTA    (PAN)",
      "Extension": "5076",
      "Titulo": "DIP.",
      "NombreCompleto": "FELIPE TORRES JOANNA ALEJANDRA  ",
      "Nombre": "FELIPE TORRES JOANNA ALEJANDRA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "joanna.felipe@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 14,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 7,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "VICEPRESIDENTA    (PRI)",
      "Extension": "5029",
      "Titulo": "DIP.",
      "NombreCompleto": "ALCAL� RUIZ BLANCA MAR�A DEL SOCORRO  ",
      "Nombre": "ALCAL� RUIZ BLANCA MAR�A DEL SOCORRO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "blanca.alcala@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 15,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 8,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIA   (MORENA)",
      "Extension": "53109",
      "Titulo": "DIP.",
      "NombreCompleto": "ESPINOZA L�PEZ BRENDA  ",
      "Nombre": "ESPINOZA L�PEZ BRENDA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "brenda.espinoza@diputados.gob.mx",
      "Edificio": "C",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 16,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 9,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIA    (PAN)",
      "Extension": "8310",
      "Titulo": "DIP.",
      "NombreCompleto": "GUTI�RREZ VALTIERRA DIANA ESTEFAN�A  ",
      "Nombre": "GUTI�RREZ VALTIERRA DIANA ESTEFAN�A",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "estefania.gutierrez@diputados.gob.mx",
      "Edificio": "G",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 17,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 10,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIA    (PRI)",
      "Extension": "8268",
      "Titulo": "DIP.",
      "NombreCompleto": "GUERRERO ESQUIVEL FUENSANTA GUADALUPE  ",
      "Nombre": "GUERRERO ESQUIVEL FUENSANTA GUADALUPE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "fuensanta.guerrero@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 18,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 11,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIA    (PVEM)",
      "Extension": "5080",
      "Titulo": "DIP.",
      "NombreCompleto": "FERN�NDEZ CRUZ NAYELI ARLEN  ",
      "Nombre": "FERN�NDEZ CRUZ NAYELI ARLEN",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "nayeli.fernandez@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 19,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 12,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIO    (PT)",
      "Extension": "53007",
      "Titulo": "DIP.",
      "NombreCompleto": "V�ZQUEZ GONZ�LEZ PEDRO  ",
      "Nombre": "V�ZQUEZ GONZ�LEZ PEDRO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "pedro.vazquez@diputados.gob.mx",
      "Edificio": "C",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 20,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 12,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIA    (MOV. CIUD.)",
      "Extension": "53068",
      "Titulo": "DIP.",
      "NombreCompleto": "ORTEGA DE LA CRUZ JESSICA MAR�A GUADALUPE  ",
      "Nombre": "ORTEGA DE LA CRUZ JESSICA MAR�A GUADALUPE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jessica.ortega@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 21,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 13,
      "Area": "PRESIDENCIA DE LA MESA DIRECTIVA",
      "Cargo": "SECRETARIA    (PRD)",
      "Extension": "5078",
      "Titulo": "DIP.",
      "NombreCompleto": "ESPINOSA MORALES OLGA LUZ  ",
      "Nombre": "ESPINOSA MORALES OLGA LUZ",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "olga.espinosa@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 22,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 14,
      "Area": "JUNTA DE COORDINACI�N POL�TICA",
      "Cargo": "PRESIDENTE    (PAN)",
      "Extension": "1862",
      "Titulo": "DIP.",
      "NombreCompleto": "ROMERO HERRERA JORGE  ",
      "Nombre": "ROMERO HERRERA JORGE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jromero.herrera@diputados.gob.mx",
      "Edificio": "G",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 23,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 15,
      "Area": "JUNTA DE COORDINACI�N POL�TICA",
      "Cargo": "SECRETARIO DE ENLACE",
      "Extension": "4240",
      "Titulo": "LIC.",
      "NombreCompleto": "S�NCHEZ MOLINA JOS� OMAR  ",
      "Nombre": "S�NCHEZ MOLINA JOS� OMAR",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jose.sanchez@diputados.gob.mx",
      "Edificio": "G",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 24,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 16,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "TITULAR DE LA UNIDAD DE TRANSPARENCIA",
      "Extension": "8132",
      "Titulo": "MTRO.",
      "NombreCompleto": "�LVAREZ MONTIEL RICARDO  ",
      "Nombre": "�LVAREZ MONTIEL RICARDO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "ricardo.alvarez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 27,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 17,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "DIRECTOR DE ATENCI�N A SOLICITUDES Y RECURSOS DE REVISI�N",
      "Extension": "66149",
      "Titulo": "LIC.",
      "NombreCompleto": "ROJAS S�NCHEZ LUIS DANIEL  ",
      "Nombre": "ROJAS S�NCHEZ LUIS DANIEL",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "luis.rojas@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 28,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 18,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "SUBDIRECTORA DE ACCESO A LA INFORMACI�N, DERECHOS ARCO Y MEDIO DE IMPUGNACI�N",
      "Extension": "8129",
      "Titulo": "LIC.",
      "NombreCompleto": "JIM�NEZ ZARI��N YESSICA  ",
      "Nombre": "JIM�NEZ ZARI��N YESSICA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "yessica.jimenez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 29,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 19,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "DIRECTORA DE TRANSPARENCIA, COORDINACI�N INTERINSTITUCIONAL, NORMATIVIDAD Y CAPACITACI�N",
      "Extension": "55032",
      "Titulo": "MTRA.",
      "NombreCompleto": "CASTILLO POSADA JACQUELINE  ",
      "Nombre": "CASTILLO POSADA JACQUELINE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jacqueline.castillo@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 32,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 20,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "SUBDIRECTOR DE TRANSPARENCIA, COORDINACI�N INTERINSTITUCIONAL, NORMATIVIDAD Y CAPACITACI�N",
      "Extension": "55085",
      "Titulo": "LIC.",
      "NombreCompleto": "GONZ�LEZ MEDINA IRVING  ",
      "Nombre": "GONZ�LEZ MEDINA IRVING",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "irving.gonzalez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 33,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 21,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "DIRECTORA DE DATOS PERSONALES, ARCHIVO Y GESTI�N DOCUMENTAL",
      "Extension": "62152",
      "Titulo": "LIC.",
      "NombreCompleto": "AGUILERA ORTA VER�NICA  ",
      "Nombre": "AGUILERA ORTA VER�NICA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "veronica.aguilera@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 36,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 22,
      "Area": "UNIDAD DE TRANSPARENCIA DE LA C�MARA DE DIPUTADOS",
      "Cargo": "SUBDIRECTORA DE DATOS PERSONALES, ARCHIVO Y GESTI�N DOCUMENTAL",
      "Extension": "67306",
      "Titulo": "LIC.",
      "NombreCompleto": "SANTILL�N ARANDA YURITZI ALEJANDRA  ",
      "Nombre": "SANTILL�N ARANDA YURITZI ALEJANDRA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "yuritzi.santillan@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 37,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 23,
      "Area": "COMIT� DE TRANSPARENCIA",
      "Cargo": "DIRECTORA DE ENLACE Y ATENCI�N DE LOS ASUNTOS ENCOMENDADOS AL COMIT� DE TRANSPARENCIA",
      "Extension": "55299",
      "Titulo": "LIC.",
      "NombreCompleto": "ARMEND�RIZ VALVERDE ALIN DE GUADALUPE  ",
      "Nombre": "ARMEND�RIZ VALVERDE ALIN DE GUADALUPE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "alin.armendariz@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 2",
      "Fotografia": null,
      "OrdenPuesto": 39,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 24,
      "Area": "COORDINACI�N DE COMUNICACI�N SOCIAL",
      "Cargo": "COORDINADOR",
      "Extension": "1339",
      "Titulo": "LIC.",
      "NombreCompleto": "ARVIZU MAR�N EDUARDO ANTONIO  ",
      "Nombre": "ARVIZU MAR�N EDUARDO ANTONIO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "eduardo.arvizu@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 41,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 25,
      "Area": "COORDINACI�N DE COMUNICACI�N SOCIAL",
      "Cargo": "COORDINADORA T�CNICA",
      "Extension": "1338",
      "Titulo": "LIC.",
      "NombreCompleto": "PULIDO TEJEDA PATRICIA  ",
      "Nombre": "PULIDO TEJEDA PATRICIA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": null,
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 43,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 26,
      "Area": "DIRECCI�N GENERAL DE INFORMACI�N",
      "Cargo": "DIRECTOR GENERAL",
      "Extension": "1332",
      "Titulo": "LIC.",
      "NombreCompleto": "G�MEZ HERRERA ALFONSO  ",
      "Nombre": "G�MEZ HERRERA ALFONSO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "alfonso.gomez@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 45,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 27,
      "Area": "DIRECCI�N DE INFORMACI�N",
      "Cargo": "DIRECTORA",
      "Extension": "2155",
      "Titulo": "LIC.",
      "NombreCompleto": "CRUZ LAZCANO MAR�A GUADALUPE  ",
      "Nombre": "CRUZ LAZCANO MAR�A GUADALUPE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "guadalupec.lazcano@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 46,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 28,
      "Area": "DIRECCI�N DE INFORMACI�N",
      "Cargo": "SUBDIRECTOR DE INFORMACI�N",
      "Extension": "2101",
      "Titulo": "LIC.",
      "NombreCompleto": "CRUZ P�REZ F�LIX MARIANO  ",
      "Nombre": "CRUZ P�REZ F�LIX MARIANO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "mariano.cruz@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 47,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 29,
      "Area": "DIRECCI�N DE INFORMACI�N",
      "Cargo": "SUBDIRECTOR DE S�NTESIS INFORMATIVA",
      "Extension": "1364",
      "Titulo": "LIC.",
      "NombreCompleto": "CASTRO OJEDA HERMENEGILDO  ",
      "Nombre": "CASTRO OJEDA HERMENEGILDO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": null,
      "Edificio": "C",
      "Piso": "BASA.",
      "Fotografia": null,
      "OrdenPuesto": 51,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 30,
      "Area": "DIRECCI�N DE INFORMACI�N",
      "Cargo": "SUBDIRECTOR DE AGENCIA DE NOTICIAS",
      "Extension": "2111",
      "Titulo": "C.",
      "NombreCompleto": "CARRASCO ARAIZAGA NORBERTO  ",
      "Nombre": "CARRASCO ARAIZAGA NORBERTO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "norberto.carrasco@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 54,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 31,
      "Area": "DIRECCI�N DE RELACIONES P�BLICAS",
      "Cargo": "DIRECTOR",
      "Extension": "2191",
      "Titulo": "C.",
      "NombreCompleto": "VALENCIA LABASTIDA CARLOS  ",
      "Nombre": "VALENCIA LABASTIDA CARLOS",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "carlos.valencia@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 55,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 32,
      "Area": "DIRECCI�N GENERAL EDITORIAL Y DE IMAGEN LEGISLATIVA",
      "Cargo": "DIRECTORA GENERAL",
      "Extension": "1464",
      "Titulo": "MTRA.",
      "NombreCompleto": "RIQUELME FERN�NDEZ ROC�O ETHEL  ",
      "Nombre": "RIQUELME FERN�NDEZ ROC�O ETHEL",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "ethel.riquelme@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 58,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 33,
      "Area": "DIRECCI�N DE DIFUSI�N",
      "Cargo": "DIRECTORA",
      "Extension": "1354",
      "Titulo": "LIC.",
      "NombreCompleto": "MAGALLANES ALVA MARTHA HILDA  ",
      "Nombre": "MAGALLANES ALVA MARTHA HILDA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "martha.magallanes@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 3",
      "Fotografia": null,
      "OrdenPuesto": 59,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 34,
      "Area": "DIRECCI�N DE DIFUSI�N",
      "Cargo": "SUBDIRECTOR DE RADIO Y TELEVISI�N",
      "Extension": "2107",
      "Titulo": "LIC.",
      "NombreCompleto": "DOM�NGUEZ CORDERO JOS� ARNULFO  ",
      "Nombre": "DOM�NGUEZ CORDERO JOS� ARNULFO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jose.dominguez@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "BASA.",
      "Fotografia": null,
      "OrdenPuesto": 60,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 35,
      "Area": "DIRECCI�N DE DIFUSI�N",
      "Cargo": "SUBDIRECTOR DE PRODUCCI�N",
      "Extension": "5005",
      "Titulo": "LIC.",
      "NombreCompleto": "P�REZ M�NDEZ CARLOS ALBERTO  ",
      "Nombre": "P�REZ M�NDEZ CARLOS ALBERTO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "carlosalberto.perez@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 3",
      "Fotografia": null,
      "OrdenPuesto": 61,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 36,
      "Area": "DIRECCI�N DE DIFUSI�N",
      "Cargo": "SUBDIRECTOR DE TRANSMISI�N Y OPERACI�N",
      "Extension": "6024",
      "Titulo": "LIC.",
      "NombreCompleto": "VILLANUEVA Y��EZ ALEJANDRO  ",
      "Nombre": "VILLANUEVA Y��EZ ALEJANDRO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "alejandro.villanueva@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "PISO 3",
      "Fotografia": null,
      "OrdenPuesto": 64,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 37,
      "Area": "DIRECCI�N DE DIFUSI�N",
      "Cargo": "SUBDIRECTOR DE PUBLICIDAD",
      "Extension": "2160",
      "Titulo": "C.",
      "NombreCompleto": "ITURBE VEL�ZQUEZ RODOLFO  ",
      "Nombre": "ITURBE VEL�ZQUEZ RODOLFO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "rodolfo.iturbide@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "P.BAJA",
      "Fotografia": null,
      "OrdenPuesto": 66,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 38,
      "Area": "DIRECCI�N DE ADMINISTRACI�N DE COMUNICACI�N SOCIAL",
      "Cargo": "DIRECTOR",
      "Extension": "1395",
      "Titulo": "LIC.",
      "NombreCompleto": "SALCEDA RUANOVA JORGE  ",
      "Nombre": "SALCEDA RUANOVA JORGE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jorge.salceda@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "BASA.",
      "Fotografia": null,
      "OrdenPuesto": 69,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 39,
      "Area": "DIRECCI�N DE ADMINISTRACI�N DE COMUNICACI�N SOCIAL",
      "Cargo": "SUBDIRECTOR DE RECURSOS HUMANOS Y CONTABILIDAD",
      "Extension": "52167",
      "Titulo": "C.P.",
      "NombreCompleto": "S�NCHEZ REBOLLAR CARLOS ALBERTO  ",
      "Nombre": "S�NCHEZ REBOLLAR CARLOS ALBERTO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "carlos.rebollar@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "BASA.",
      "Fotografia": null,
      "OrdenPuesto": 70,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 40,
      "Area": "DIRECCI�N DE ADMINISTRACI�N DE COMUNICACI�N SOCIAL",
      "Cargo": "SUBDIRECTOR DE RECURSOS  MATERIALES Y SERVICIOS",
      "Extension": "51153",
      "Titulo": "LIC.",
      "NombreCompleto": "MART�NEZ GUERRERO ARTURO  ",
      "Nombre": "MART�NEZ GUERRERO ARTURO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "arturo.martinez@diputados.gob.mx",
      "Edificio": "A",
      "Piso": "BASA.",
      "Fotografia": null,
      "OrdenPuesto": 72,
      "OidSeccion": "466af8b0-fbe9-4302-8893-1317b3e957ed",
      "__typename": "DirectorioFull"
    },
    {
      "id": 41,
      "Area": "SECRETAR�A GENERAL",
      "Cargo": "SECRETARIA GENERAL",
      "Extension": "5014",
      "Titulo": "LIC.",
      "NombreCompleto": "B�EZ RIC�RDEZ GRACIELA  ",
      "Nombre": "B�EZ RIC�RDEZ GRACIELA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "graciela.baez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 1",
      "Fotografia": null,
      "OrdenPuesto": 75,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 42,
      "Area": "SECRETAR�A GENERAL",
      "Cargo": "COORDINADOR DE ASESORES",
      "Extension": "4469",
      "Titulo": "DR.",
      "NombreCompleto": "FLORES MEZA JOS� RUB�N  ",
      "Nombre": "FLORES MEZA JOS� RUB�N",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "ruben.flores@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 1",
      "Fotografia": null,
      "OrdenPuesto": 78,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 43,
      "Area": "DIRECCI�N GENERAL DE ASUNTOS JUR�DICOS",
      "Cargo": "DIRECTOR GENERAL",
      "Extension": "54106",
      "Titulo": "MTRO.",
      "NombreCompleto": "V�SQUEZ RODR�GUEZ LUIS GENARO  ",
      "Nombre": "V�SQUEZ RODR�GUEZ LUIS GENARO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "genaro.vasquez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 86,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 44,
      "Area": "DIRECCI�N GENERAL DE ASUNTOS JUR�DICOS",
      "Cargo": "COORDINADOR  T�CNICO",
      "Extension": "54101",
      "Titulo": "MTRO.",
      "NombreCompleto": "CURIEL HERNANDEZ JOS� ANTONIO  ",
      "Nombre": "CURIEL HERNANDEZ JOS� ANTONIO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "antonio.curiel@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 87,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 45,
      "Area": "DIRECCI�N GENERAL DE ASUNTOS JUR�DICOS",
      "Cargo": "SUBDIRECTORA DE ASUNTOS JUR�DICOS",
      "Extension": "54103",
      "Titulo": "MTRA.",
      "NombreCompleto": "HERN�NDEZ RAM�REZ ANA MONSERRAT  ",
      "Nombre": "HERN�NDEZ RAM�REZ ANA MONSERRAT",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "monserrat.hernandez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 88,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 46,
      "Area": "DIRECCI�N DE SERVICIOS LEGALES",
      "Cargo": "DIRECTOR",
      "Extension": "54134",
      "Titulo": "MTRO.",
      "NombreCompleto": "PICHARDO MORA OLINSSER ELIHU  ",
      "Nombre": "PICHARDO MORA OLINSSER ELIHU",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "olinsser.pichardo@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 95,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 47,
      "Area": "DIRECCI�N DE SERVICIOS LEGALES",
      "Cargo": "SUBDIRECTORA DE APOYO NORMATIVO",
      "Extension": "54233",
      "Titulo": "MTRA.",
      "NombreCompleto": "AZAR CRUZ CLAUDIA VIOLETA  ",
      "Nombre": "AZAR CRUZ CLAUDIA VIOLETA",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "claudia.azar@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 96,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 48,
      "Area": "DIRECCI�N DE SERVICIOS LEGALES",
      "Cargo": "SUBDIRECTOR DE CONTRATOS Y CONVENIOS",
      "Extension": "54082",
      "Titulo": "LIC.",
      "NombreCompleto": "V�ZQUEZ RAZO JUAN CARLOS  ",
      "Nombre": "V�ZQUEZ RAZO JUAN CARLOS",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "juan.vazquez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 97,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 49,
      "Area": "DIRECCI�N DE LO CONSULTIVO Y ASESOR�A JUR�DICA",
      "Cargo": "DIRECTOR",
      "Extension": "68382",
      "Titulo": "DR.",
      "NombreCompleto": "RUIZ MUNILLA JOS� DE JES�S  ",
      "Nombre": "RUIZ MUNILLA JOS� DE JES�S",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "jesus.ruiz@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 100,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 50,
      "Area": "DIRECCI�N DE LO CONSULTIVO Y ASESOR�A JUR�DICA",
      "Cargo": "SUBDIRECTOR DE LO CONSULTIVO Y ASESOR�A JUR�DICA",
      "Extension": "68382",
      "Titulo": "LIC.",
      "NombreCompleto": "RUIZ RAM�REZ JOSIMAR NASAE  ",
      "Nombre": "RUIZ RAM�REZ JOSIMAR NASAE",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "josimar.ruiz@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 101,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 51,
      "Area": "DIRECCI�N DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
      "Cargo": "DIRECTOR",
      "Extension": "54158",
      "Titulo": "MTRO.",
      "NombreCompleto": "L�PEZ FALC�N EDUARDO  ",
      "Nombre": "L�PEZ FALC�N EDUARDO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "eduardo.lopez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 102,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 52,
      "Area": "DIRECCI�N DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
      "Cargo": "SUBDIRECTOR DE CONTROVERSIAS Y PROCEDIMIENTOS CONSTITUCIONALES",
      "Extension": "54122",
      "Titulo": "LIC.",
      "NombreCompleto": "RUIZ ARIAS SERGIO  ",
      "Nombre": "RUIZ ARIAS SERGIO",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "sergio.ruiz@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 103,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 53,
      "Area": "DIRECCI�N DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
      "Cargo": "SUBDIRECTOR DE AMPAROS",
      "Extension": "54153",
      "Titulo": "LIC.",
      "NombreCompleto": "URIBE MEJ�A JUAN  ",
      "Nombre": "URIBE MEJ�A JUAN",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "juan.uribe@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 104,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    },
    {
      "id": 54,
      "Area": "DIRECCI�N DE LO CONTENCIOSO Y PROCEDIMIENTOS CONSTITUCIONALES",
      "Cargo": "SUBDIRECTOR DE ASUNTOS LABORALES",
      "Extension": "54152",
      "Titulo": "LIC.",
      "NombreCompleto": "P�REZ APARICIO �NGEL MART�N  ",
      "Nombre": "P�REZ APARICIO �NGEL MART�N",
      "APaterno": null,
      "Amaterno": null,
      "Correo": "angel.perez@diputados.gob.mx",
      "Edificio": "E",
      "Piso": "PISO 4",
      "Fotografia": null,
      "OrdenPuesto": 105,
      "OidSeccion": "22ca1099-e515-42f0-80eb-e6d70aef7047",
      "__typename": "DirectorioFull"
    }
]

module.exports = personal